export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_LIST_SHIPPER_REQUEST = "ORDER_LIST_SHIPPER_REQUEST";
export const ORDER_LIST_SHIPPER_SUCCESS = "ORDER_LIST_SHIPPER_SUCCESS";
export const ORDER_LIST_SHIPPER_FAIL = "ORDER_LIST_SHIPPER_FAIL";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";
export const ORDER_DELETE_RESET = "ORDER_DELETE_FAIL";

// HIDDEN ORDER
export const ORDER_HIDDEN_REQUEST = "ORDER_HIDDEN_REQUEST";
export const ORDER_HIDDEN_SUCCESS = "ORDER_HIDDEN_SUCCESS";
export const ORDER_HIDDEN_FAIL = "ORDER_HIDDEN_FAIL";
export const ORDER_HIDDEN_RESET = "ORDER_HIDDEN_FAIL";

// SHOW ORDER
export const ORDER_SHOW_REQUEST = "ORDER_SHOW_REQUEST";
export const ORDER_SHOW_SUCCESS = "ORDER_SHOW_SUCCESS";
export const ORDER_SHOW_FAIL = "ORDER_SHOW_FAIL";
export const ORDER_SHOW_RESET = "ORDER_SHOW_FAIL";

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL";
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET";

export const ORDER_CONFIRM_REQUEST = "ORDER_CONFIRM_REQUEST";
export const ORDER_CONFIRM_SUCCESS = "ORDER_CONFIRM_SUCCESS";
export const ORDER_CONFIRM_FAIL = "ORDER_CONFIRM_FAIL";
export const ORDER_CONFIRM_RESET = "ORDER_CONFIRM_RESET";

export const ORDER_ADMIN_CANCEL_REQUEST = "ORDER_ADMIN_CANCEL_REQUEST";
export const ORDER_ADMIN_CANCEL_SUCCESS = "ORDER_ADMIN_CANCEL_SUCCESS";
export const ORDER_ADMIN_CANCEL_FAIL = "ORDER_ADMIN_CANCEL_FAIL";
export const ORDER_ADMIN_CANCEL_RESET = "ORDER_ADMIN_CANCEL_RESET";

export const ORDER_USER_CANCEL_REQUEST = "ORDER_USER_CANCEL_REQUEST";
export const ORDER_USER_CANCEL_SUCCESS = "ORDER_USER_CANCEL_SUCCESS";
export const ORDER_USER_CANCEL_FAIL = "ORDER_USER_CANCEL_FAIL";
export const ORDER_USER_CANCEL_RESET = "ORDER_USER_CANCEL_RESET";

export const ORDER_SELECT_SHIPPER_REQUEST = "ORDER_SELECT_SHIPPER_REQUEST";
export const ORDER_SELECT_SHIPPER_SUCCESS = "ORDER_SELECT_SHIPPER_SUCCESS";
export const ORDER_SELECT_SHIPPER_FAIL = "ORDER_SELECT_SHIPPER_FAIL";
export const ORDER_SELECT_SHIPPER_RESET = "ORDER_SELECT_SHIPPER_RESET";
