export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_VERIFY = "USER_REGISTER_VERIFY";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_UPDATE_ROLE_REQUEST = "USER_UPDATE_ROLE_REQUEST";
export const USER_UPDATE_ROLE_SUCCESS = "USER_UPDATE_ROLE_SUCCESS";
export const USER_UPDATE_ROLE_FAIL = "USER_UPDATE_ROLE_FAIL";
export const USER_UPDATE_ROLE_RESET = "USER_UPDATE_ROLE_RESET";

export const USER_UPDATE_AVATAR_REQUEST = "USER_UPDATE_AVATAR_REQUEST";
export const USER_UPDATE_AVATAR_SUCCESS = "USER_UPDATE_AVATAR_SUCCESS";
export const USER_UPDATE_AVATAR_FAIL = "USER_UPDATE_AVATAR_FAIL";

export const USER_GET_ADDRESS_DATA_REQUEST = "USER_GET_ADDRESS_DATA_REQUEST";
export const USER_GET_ADDRESS_DATA_SUCCESS = "USER_GET_ADDRESS_DATA_SUCCESS";
export const USER_GET_ADDRESS_DATA_FAIL = "USER_GET_ADDRESS_DATA_FAIL";

export const USER_UPDATE_PASSWORD_REQUEST = "USER_UPDATE_PASSWORD_REQUEST";
export const USER_UPDATE_PASSWORD_SUCCESS = "USER_UPDATE_PASSWORD_SUCCESS";
export const USER_UPDATE_PASSWORD_FAIL = "USER_UPDATE_PASSWORD_FAIL";
export const USER_UPDATE_PASSWORD_RESET = "USER_UPDATE_PASSWORD_RESET";

export const USER_FORGOT_PASSWORD_REQUEST = "USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAIL = "USER_FORGOT_PASSWORD_FAIL";
export const USER_FORGOT_PASSWORD_RESET = "USER_FORGOT_PASSWORD_RESET";

export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST";
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL";
export const USER_RESET_PASSWORD_RESET = "USER_RESET_PASSWORD_RESET";

export const USER_DISABLE_REQUEST = "USER_DISABLE_REQUEST";
export const USER_DISABLE_SUCCESS = "USER_DISABLE_SUCCESS";
export const USER_DISABLE_FAIL = "USER_DISABLE_FAIL";

export const ADMIN_GET_USER_DETAILS_REQUEST = "ADMIN_GET_USER_DETAILS_REQUEST";
export const ADMIN_GET_USER_DETAILS_SUCCESS = "ADMIN_GET_USER_DETAILS_SUCCESS";
export const ADMIN_GET_USER_DETAILS_FAIL = "ADMIN_GET_USER_DETAILS_FAIL";
export const ADMIN_ADD_STAFF_REQUEST = "ADMIN_ADD_STAFF_REQUEST";
export const ADMIN_ADD_STAFF_SUCCESS = "ADMIN_ADD_STAFF_SUCCESS";
export const ADMIN_ADD_STAFF_FAIL = "ADMIN_ADD_STAFF_FAIL";
